apiVersion: v1
kind: Service
metadata:
  name: service-devops
  labels:
    app: devops-psu
  namespace: devops-psu
spec:
  type: LoadBalancer
  selector:
    app: devops-psu
    svc: frontend
  ports:
  - port: 12345
    targetPort: 8000
  externalIPs:
  - 10.0.2.15